version: '3'

services:
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    tty: true
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    - MYSQL_DATABASE=${DB_NAME}
    - MYSQL_USER=${DB_USERNAME}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
    - "./docker/mysql:/var/lib/mysql"
    ports:
    - '${APP_PORT}:3306'
    container_name: mysql