version: '3'
services:
    web:
        build:
            context: ./docker/nginx/
        ports:
        - '${APP_PORT}:80'
        - '${APP_PORT_SSL}:443'
        volumes:
        - './public_html/${PROJECT_FOLDER}:/var/www/html/'
        - './docker/nginx/conf/:/etc/nginx/conf.d/'
        - './docker/nginx/ssl/:/etc/nginx/certs/'
        depends_on: 
        - php
    php:
        build:
            context: ./docker/php/
            args:
                PHP_VERSION: ${PHP_VERSION}
        extra_hosts:
            - 'host.docker.internal:${HOST_DOCKER_INTERNAL}'
            - 'api.wordpress.org:198.143.164.251'
        volumes:
        - './public_html/${PROJECT_FOLDER}:/var/www/html/'
        - './docker/php/conf/:/usr/local/etc/php/conf.d/'
